### ISSUE TITLE
Incompatibility with CF7 version 4.2 - From WP Support forum

### ISSUE THREAD

**Issue by jessepearson** [jessepearson/mailpoet-contact-form-7#18]
https://wordpress.org/support/topic/incompatibility-with-cf7-version-42

People believe this project/plugin has been abandoned.

**Comment by BFTrick** [comment]
@jessepearson I don't maintain this any longer. I'd be happy to add you as a contributor if you wanted to help maintain it. :)

**Comment by jessepearson** [comment]
@BFTrick Here or over on the WP repository?

**Comment by BFTrick** [comment]
I can give you contributor access to both. Would be good to do everything here and then push it to wp.org. Sound good?

**Comment by jessepearson** [comment]
Sounds good.

Not going to lie, I haven't done anything with the WP repo before and my git skills are lacking since I rarely use it. As long as there are docs, I can do it all, though.

**Comment by BFTrick** [comment]
Cool - start with a [pull request](https://help.github.com/articles/using-pull-requests/). :)

**Comment by jessepearson** [comment]
Done, but I am sure you got the notice.

**Comment by BFTrick** [comment]
Awesome job! I've added you as a committer here and on WordPress.org. 

Next step: updating the changelog & version numbers.

Next step: push it up to WordPress.org. :)

**Comment by jessepearson** [comment]
I actually just realized something. Here in github the version says 1.0.3 and over on WP it says 1.0.5. It appears that Mail Poet has published updates beyond what was here, and my changes are based off of what was here, so I am going to need to do some additional updates. Fun.

**Comment by BFTrick** [comment]
The opposite of fun. I'd reach out to MailPoet. They've had a private mirror of this repo but it does no one any good if they don't keep both up to date. If they're okay with it let's shut this one down and make theirs public.

**Comment by jessepearson** [comment]
Luckily my client has a premium account, so I was able to email them directly...they are really closed off about that. A little underhanded on my part, but the plugin is broken and I also need a "live" fix for my client's site.

**Comment by jessepearson** [comment]
So, I checked out the version in the WP repo, updated it and submitted the change yesterday. It's been 15 hours and no more tickets have come in, I guess that means I did well.

I believe this repo should remain active and the MP team should collab here, then push to WP. That way others in the future can help with fixes, enhancements, etc in future (just like I am).

**Comment by BFTrick** [comment]
Awesome job Jesse! :D I'm happy giving up this plugin. I could give you admin access to the WP repo and the GitHub repo. Then you can manage it however you like. You may want to remove their access so they can't use their own private repo and get out of sync.

**Comment by jessepearson** [comment]
That works, go ahead and give me admin access. 

I will talk to them about this repo. The person I was conversing with said they didn't know about this one and that's why it wasn't used.

**Comment by BFTrick** [comment]
I can't transfer this repo until you delete your fork. Can you please do that and I'll transfer it to you entirely?

**Comment by jessepearson** [comment]
Your repository "jessepearson/mailpoet-contact-form-7" was successfully deleted.

Should be good to go. Sorry I took so long.
