### ISSUE TITLE
Can the label be inside the span, please? (If not, why not?)

### ISSUE THREAD

**Issue by wgdes** [jessepearson/mailpoet-contact-form-7#22]
I have a problem with an effect caused by this line of code:
`<span class="wpcf7-form-control-wrap %1$s"><input type="checkbox" %2$s />&nbsp;</span><label for="%3$s">%4$s</label>`

Why can't the label be *inside* the `wpcf7-form-control-wrap` span? I'm having some CSS issues that would be easily resolved if the input and label were a sibling pair.

Any help would be greatly appreciated.

**Comment by jessepearson** [comment]
Just pushed a new version live here. It adds a checkbox when adding the shortcode in the contact form. It will add an additional parameter that, if present, will change the label to be inside of the span.

The new shortcode should resemble:
`[mailpoetsignup mailpoetsignup-952 label-inside-span]`

Test out the new version and let me know if this resolves your issue. I know how much of a pain it can be to style items output by plugins :)

**Comment by wgdes** [comment]
Perfect! It works exactly as I need it now. Thank you so much! :)

**Comment by jessepearson** [comment]
Sweet, I will push the changes to the WP repo later today or tomorrow. 

If you do a lot of WP theme/plugin work, check out this plugin to see if it is any use to you: https://wordpress.org/support/plugin/wp-simple-debug
