### ISSUE TITLE
Hide the checkbox when having only one list

### ISSUE THREAD

**Issue by kevinmamaqi** [jessepearson/mailpoet-contact-form-7#23]
I think that letting users to have the option to choose between different lists is ok, but when there's only one list, it doesn't make sense (or at least I don't understand it). The topic is closed, so I decided to post here - https://wordpress.org/support/topic/checkbox-without-content-in-registration-form

**Comment by jessepearson** [comment]
The topic over on the WP support forum appears to be about someone that's wanting to sign people up without them having to check off a box, but it seems like you're asking about the multiple checkboxes for the different lists when adding the field to the form. 

There is only one checkbox that is added on the front end in the form, and it is for the site visitor to optionally join the mailing list(s) that have been chosen by a site admin.

Let me know if I am misunderstanding you.

**Comment by kevinmamaqi** [comment]
No, sorry. Maybe I misunderstood the other topic, I have only one list, so, What is the point to have a checkbox?

**Comment by jessepearson** [comment]
This plugin ties two other plugins together, Contact Form 7 and MailPoet. The checkbox is an opt in mechanism which allows you to allow users to subscribe to your newsletter when they are submitting a contact form. This plugin is not strictly just for signing people up to the newsletter, MailPoet provides those forms and widgets. 

It does have the option of having the box checked by default, then the user would need to uncheck the box if they don't want to join the newsletter.

**Comment by kevinmamaqi** [comment]
Ok, understood. I was using the plugin just for signing people to the newsletter.

**Comment by jessepearson** [comment]
If you still wanted to use this plugin with CF7 to do your signup form, you could hide the checkbox via CSS.
